"""
G360 Horas Extras - Configuration Module
Theme, colors, and styling constants.
"""

from .theme import (
    G360_GREEN, G360_DARK, G360_CARD_BG, G360_TEXT, G360_GRAY, G360_RED, G360_BLUE,
    G360_GREEN_HOVER,
    BG_LABORABLE, BG_SABADO, BG_DOMINGO, BG_FERIADO,
    COLOR_LABORABLE_TEXTO, COLOR_SABADO_TEXTO, COLOR_DOMINGO_TEXTO, COLOR_FERIADO_TEXTO,
    FONT_FAMILY_PRIMARY, FONT_FAMILY_FALLBACK, FONT_FAMILY_MONO,
    FONT_SIZE_HEADER, FONT_SIZE_TITLE, FONT_SIZE_BODY, FONT_SIZE_SMALL, FONT_SIZE_LABEL,
    WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_RESIZABLE,
    CARD_CORNER_RADIUS, BUTTON_HEIGHT, BUTTON_HEIGHT_LARGE,
    PADDING_X, PADDING_Y,
    LEGEND_ITEMS
)
